// ===============
// Lists
// ===============

// The order of these lists is the order they will be displayed, you can change the order but...
// The object keys ('a' 'b' etc.) are the identifers, NEVER change their values to something different than it's meaning.
// Ex. You can change 'a': 'Prefer not to say' to 'a': 'I'd rather not say', but do not change it to 'a': 'Male'.
// Sequence is 'a', 'b', 'c' ... 'z', 'aa', 'ab', 'ac' ... 'aaa', etc. (Like Excel).
// The 'Opt-Out' type choice (Prefer not to say / Not sure) should preferably come first in the lists.

const lists = {
    genders: {
        'a': 'Prefer not to say',
        'b': 'Male',
        'c': 'Female',
        'd': 'Gender Queer/Other'
    },
    pronouns: {
        'a': 'Prefer not to say',
        'b': 'He/His',
        'c': 'She/Her',
        'd': 'They/Them',
    },
    looking_for: {
        'a': 'Not sure yet',
        'b': 'Band mates',
        'c': 'Make friends',
        'd': 'Concert buddies',
        'e': 'Chats',
        'f': 'New music',
        'g': 'Local music',
        'h': 'Jam buddies',
        'i': 'Music discussion',
    },
    genres: {
        'a': 'pop',
        'b': 'dance pop',
        'c': 'rap',
        'd': 'pop dance',
        'e': 'pop rap',
        'f': 'rock',
        'g': 'post-teen pop',
        'h': 'latin',
        'i': 'hip hop',
        'j': 'modern rock',
        'k': 'trap latino',
        'l': 'trap',
        'm': 'reggaeton',
        'n': 'pop rock',
        'o': 'edm',
        'p': 'vaporwave',
        'q': 'latin pop',
        'r': 'tropical house',
        's': 'classic rock',
        't': 'album rock',
        'u': 'mellow gold',
        'v': 'soft rock',
        'w': 'melodic rap',
        'x': 'electropop',
        'y': 'indie pop',
        'z': 'tropical',
        'aa': 'alternative metal',
        'ab': 'r&b',
        'ac': 'k-pop',
        'ad': 'electro house',
        'ae': 'contemporary country',
        'af': 'urban contemporary',
        'ag': 'uk pop',
        'ah': 'hard rock',
        'ai': 'neo mellow',
        'aj': 'nu metal',
        'ak': 'alternative rock',
        'al': 'folk rock',
        'am': 'viral pop',
        'an': 'alternative r&b',
        'ao': 'pop punk',
        'ap': 'rock en espanol',
        'aq': 'latin hip hop',
        'ar': 'modern alternative rock',
        'as': 'country',
        'at': 'underground hip hop',
        'au': 'nuevo regional mexicano',
        'av': 'gangster rap',
        'aw': 'atl hip hop',
        'ax': 'country road',
        'ay': 'dance rock',
        'az': 'new wave pop',
        'ba': 'emo rap',
        'bb': 'indie rock',
        'bc': 'art rock',
        'bd': 'reggaeton colombiano',
        'be': 'soul',
        'bf': 'house',
        'bg': 'country rock',
        'bh': 'latin alternative',
        'bi': 'mexican pop',
        'bj': 'indie folk',
        'bk': 'latin rock',
        'bl': 'art pop',
        'bm': 'big room',
        'bn': 'k-pop boy group',
        'bo': 'stomp and holler',
        'bp': 'reggaeton flow',
        'bq': 'hip pop',
        'br': 'j-pop',
        'bs': 'neo soul',
        'bt': 'francoton',
        'bu': 'indie poptimism',
        'bv': 'sertanejo',
        'bw': 'metal',
        'bx': 'pop edm',
        'by': 'post-grunge',
        'bz': 'spanish pop',
        'ca': 'new wave',
        'cb': 'blues rock',
        'cc': 'roots rock',
        'cd': 'folk',
        'ce': 'funk',
        'cf': 'rap francais',
        'cg': 'psychedelic rock',
        'ch': 'boy band',
        'ci': 'singer-songwriter',
        'cj': 'sertanejo pop',
        'ck': 'lo-fi beats',
        'cl': 'indie soul',
        'cm': 'norteno',
        'cn': 'vapor trap',
        'co': 'desi pop',
        'cp': 'quiet storm',
        'cq': 'german pop',
        'cr': 'progressive house',
        'cs': 'k-pop girl group',
        'ct': 'new romantic',
        'cu': 'motown',
        'cv': 'conscious hip hop',
        'cw': 'progressive electro house',
        'cx': 'pop r&b',
        'cy': 'talent show',
        'cz': 'rap metal',
        'da': 'sad rap',
        'db': 'disco',
        'dc': 'electronica',
        'dd': 'modern country rock',
        'de': 'indietronica',
        'df': 'punk',
        'dg': 'dark trap',
        'dh': 'social media pop',
        'di': 'christian music',
        'dj': 'metropopolis',
        'dk': 'alternative dance',
        'dl': 'brill building pop',
        'dm': 'hardcore hip hop',
        'dn': 'otacore',
        'do': 'indie cafe pop',
        'dp': 'pagode',
        'dq': 'heartland rock',
        'dr': 'worship',
        'ds': 'vocal jazz',
        'dt': 'emo',
        'du': 'metalcore',
        'dv': 'pop nacional',
        'dw': 'rap rock',
        'dx': 'lounge',
        'dy': 'soundtrack',
        'dz': 'piano rock',
        'ea': 'world worship',
        'eb': 'j-poprock',
        'ec': 'classical',
        'ed': 'folk-pop',
        'ee': 'new rave',
        'ef': 'alternative hip hop',
        'eg': 'forro',
        'eh': 'vapor soul',
        'ei': 'chillhop',
        'ej': 'christian alternative rock',
        'ek': 'mariachi',
        'el': 'melodic metalcore',
        'em': 'acoustic pop',
        'en': 'j-rock',
        'eo': 'turkish trap pop',
        'ep': 'background music',
        'eq': 'rap conscient',
        'er': 'show tunes',
        'es': 'country pop',
        'et': 'anime',
        'eu': 'grunge',
        'ev': 'electronic trap',
        'ew': 'outlaw countr',
    }
}

module.exports = {
    lists: lists,
    decipherCodes: function (list, codeString) { // Returns a string where all codes are replaced with their meaning
        if (codeString == undefined) return;
        if (codeString.includes(',')) { // If more than one in the list
            const codesArray = codeString.split(', ');
            const newArray = [];

            codesArray.forEach(code => {
                newArray.push(lists[list][code]);
            });

            const newString = newArray.join(', ');
            return newString;
        } else { // If just one in the list
            return lists[list][codeString];
        }
    }
}